server:
  port: 12000

spring:
  application:
    name: order-at-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata_at?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

logging:
  level:
    root: info
    io.seata: debug

seata:
  tx-service-group: xuegao-seata-at
